base_lr: 0.01
batch_size: 256
config: ./config/kinetics-skeleton/test_joint.yaml
device: 0
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.agcn.Model
model_args:
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 400
  num_person: 2
  num_point: 18
model_saved_name: ./work_dir/kinetics/agcn_joint_test/save_models/
nesterov: false
num_epoch: 80
num_worker: 32
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: test
print_log: true
save_interval: 2
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
- 60
test_batch_size: 64
test_feeder_args:
  data_path: ./data/kinetics/val_data_joint.npy
  debug: false
  label_path: ./data/kinetics/val_label.pkl
train_feeder_args: {}
warm_up_epoch: 0
weight_decay: 0.0005
weights: result/SOTA/kinetics/joint/epoch-57-109779.pt
work_dir: ./work_dir/kinetics/agcn_joint_test
