base_lr: 0.1
batch_size: 114
config: ./config/kinetics-skeleton/train_bone.yaml
device:
- 0
eval_interval: 1
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.agcn.Model
model_args:
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 400
  num_person: 2
  num_point: 18
model_saved_name: ./runs/ki_agcn_bone
nesterov: true
num_epoch: 80
num_worker: 32
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: train
print_log: true
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 45
- 55
test_batch_size: 114
test_feeder_args:
  data_path: ./data/kinetics/val_data_bone.npy
  label_path: ./data/kinetics/val_label.pkl
train_feeder_args:
  data_path: ./data/kinetics/train_data_bone.npy
  debug: false
  label_path: ./data/kinetics/train_label.pkl
  random_choose: true
  random_move: true
  window_size: 150
warm_up_epoch: 0
weight_decay: 0.0001
weights: null
work_dir: work_dir/kinetics/bone/SOTA
